name: Docker
on:
  pull_request:
  push:
    branches:
      - master
permissions:
  contents: read

jobs:
  build:
    name: Docker build (and optional push)
    runs-on: ubuntu-20.04
    env:
      RUBYGEMS_VERSION: 3.3.25
      RUBY_VERSION: 3.1.2
    steps:
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@c252a3bb80dae98127b9329b8aa1ff35b71ae980 # master
    - name: Cache Docker layers
      uses: actions/cache@c1a5de879eb890d062a85ee0252d6036480b1fe2 # v3.2.1
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-rubygems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-rubygems-org
    - name: Install and start services (needed for image test)
      run: docker-compose up -d
    - name: build, test and optionally push docker image
      run: ./script/build_docker.sh
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
